### ISSUE TITLE
下载代码

### ISSUE THREAD

**Issue by zinc-96** [Tp0t-Team/Tp0tOJ#48]
您好，怎么才能使用命令行下载v2.4里的所有文件呢？
我使用命令git clone --branch v2.4 https://github.com/Tp0t-Team/Tp0tOJ.git，会提示我You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by switching back to a branch.只能下载主分支的代码

**Comment by azurity** [comment]
使用`git clone --branch v2.4 https://github.com/Tp0t-Team/Tp0tOJ.git`可以正确的下载v2.4版本的代码。`v2.4`是一个`tag`而不是一个单独的分支，因此git会提示您`You are in 'detached HEAD' state`。如果您**只需要编译代码**，这个状态是**正确的**。如果您想要基于此代码开发，您完全完全可以基于`v2.4`创建一个新的分支。（不过我们更建议您基于主分支fork新分支开发而不是基于以有的发行版）

一些关于tag的介绍：[git文档](https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E6%89%93%E6%A0%87%E7%AD%BE)
