### ISSUE TITLE
Ojtool_inux_amd64 cannot be used

### ISSUE THREAD

**Issue by xiaoming-king** [Tp0t-Team/Tp0tOJ#50]
![image](https://github.com/user-attachments/assets/086b3430-3c34-43cd-9844-edef089af5dd)

May I ask if you have the source code or solution for ojtool_inux_amd64

**Comment by xiaoming-king** [comment]
> ![image](https://private-user-images.githubusercontent.com/65775367/348517842-086b3430-3c34-43cd-9844-edef089af5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDM1NDcsIm5iZiI6MTcyMTQ0MzI0NywicGF0aCI6Ii82NTc3NTM2Ny8zNDg1MTc4NDItMDg2YjM0MzAtM2MzNC00M2NkLTk4NDQtZWRlZjA4OWFmNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAyNDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOGUyN2NiZmEyMTM3ODVmNTg4NzI1ZDlhMjIwMTE5NWRiNzFiMjIxODUyNDZkZDQ3MDFhM2M1NjRhYTk1MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cvyIoV3I_YsvI5vyg8P-w5LYRAoXCh4Y2lu5QL4DRbg)
> 
> May I ask if you have the source code or solution for ojtool_inux_amd64

**Comment by LordCasser** [comment]
> 
> ![image](https://github.com/user-attachments/assets/086b3430-3c34-43cd-9844-edef089af5dd)
> 
> 
> May I ask if you have the source code or solution for ojtool_inux_amd64

That issue seems like something wrong during k3s installation.
That script is maintained by k3s. You can find the script in their website and execute it. May you can fix it out.

A quick tip: I guess you are in some shell environment but it's not bash. You can switch to bash and retry.

Hope everything is ok.

**Comment by azurity** [comment]
The old K3S installation script mirror source has invalid. I have already replaced it with a valid URL. Try the latest release (v2.4.2).

**Comment by LordCasser** [comment]
this issue will be close
